background-color=#292E2B
text-color=#E4E8E5
border-color=#39423C
progress-color=over #396E4A
border-size=2
border-radius=6
padding=12
default-timeout=7000
ignore-timeout=0

[urgency=low]
text-color=#AEB8B1

[urgency=high]
border-color=#D77A78
default-timeout=0
