background-color=#050608
text-color=#E8ECF2
border-color=#1B222C
progress-color=over #29467E
border-size=2
border-radius=6
padding=12
default-timeout=7000
ignore-timeout=0

[urgency=low]
text-color=#A9B2BE

[urgency=high]
border-color=#E17A84
default-timeout=0
