background-color=#0B0E12
text-color=#E6EAF0
border-color=#252C37
progress-color=over #314E8A
border-size=2
border-radius=6
padding=12
default-timeout=7000
ignore-timeout=0

[urgency=low]
text-color=#A9B1BD

[urgency=high]
border-color=#E17B85
default-timeout=0
